name: Jekyll site CI

on:
  push:
    branches:
      - main  # or the branch you want to deploy from

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7.0'  # Ensure this matches the Ruby version in your Gemfile.lock

    - name: Install Bundler
      run: |
        gem install bundler:2.5.12  # Use the version that created your Gemfile.lock

    - name: Install dependencies
      run: |
        bundle install

    - name: Build the site
      run: bundle exec jekyll build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site